project:
  title: "ManifoldsBase.jl Tutorials"
  output-dir: ../docs/src/tutorials
  render:
    - "*.qmd"

crossref:
  fig-prefix: Figure
  tbl-prefix: Table
bibliography:
  - ../CITATION.bib
csl: ../bib/journal-of-the-royal-statistical-society.csl
fig-format: png

execute:
  freeze: auto
  eval: true
  echo: true
  output: true


format:
  commonmark:
    variant: -raw_html+tex_math_dollars
    wrap: preserve

jupyter: julia-1.10