---
title: "What are manifolds?"
---

````{=commonmark}
```@meta
CurrentModule = ManifoldsBase
```
```@contents
Pages = ["what-are-manifolds.md"]
Depth = 3
```
````

## Introduction

A precise definition of a manifold is crucial to set up appropriate expectations for types and functions.
Unfortunately, there is no single definition that is general enough to cover all relevant cases and, at the same time, specific enough to be useful.
Here we will cover the definitions that are most relevant in practice.

The most generic relevant concept is that of a topological space.
It describes the notion of closeness of points through families of open sets which satisfy certain properties.
There are currently no functions in JuliaManifolds that can work at this level of generality.

In this tutorial we will go from the most general concepts to the ones that provide the most structure.
We will briefly discuss their relevance and provide references to more in-depth materials.
Basic knowledge of multivariate calculus, linear algebra and ordinary differential equations is required to understand this tutorial.
More advanced topics are helpful but not necessary to learn something from this text.

## Topology

The first concept that provides tools we can use is that of a topological manifold.
Such manifold ``M`` is described by its dimension ``n=manifold_dimension(M)`` and an atlas $\{\phi_i\}_{i\in I}$ where $\phi_i\colon U_i \to \mathbb{R}^n$ are homeomorphisms called charts indexed by $i$ from some index set $I$ [Lee:2012](@cite) and $U_i \subseteq \mathcal{M}$. [^chart-number-system]

For each point $p \in \mathcal{M}$ there is $i\in I$ such that $p \in U_i$.
There are also some regularity conditions that exclude certain topological spaces from being called a manifold.
Specifically they are requirements that $\mathcal{M}$ is a second-countable Hausdorff space, see [Lee:2012](@cite), page 3 for more details.

JuliaManifolds has a few functions for working at this level.
First, [`manifold_dimension`](@ref) returns the number `n` for a given manifold.
Next, ``[`get_chart_index`](@extref Manifolds :jl:method:`Manifolds.get_chart_index-Tuple{AbstractManifold, AbstractAtlas, Any, Any}`)``{=commonmark} points to one of the charts such that $p$ is in its domain.
The value of chart on a point can be calculated using ``[`get_parameters`](@extref `Manifolds.get_parameters`)``{=commonmark} and its inverse using ``[`get_point`](@extref `Manifolds.get_point`)``{=commonmark}.
When we have two charts $\phi_i, \phi_j$, the composition $\phi_j \circ \phi_i^{-1}$ is called the transition map from $\phi_i$ to $\phi_j$, see ``[`transition_map`](@extref `Manifolds.transition_map`)``{=commonmark}.
More details are discussed in [this page](https://juliamanifolds.github.io/Manifolds.jl/stable/features/atlases/) and [this tutorial](https://juliamanifolds.github.io/Manifolds.jl/stable/tutorials/working-in-charts/) demonstrates a use case.
Often additional restrictions are imposed, for example only atlases with only [differentiable](https://en.wikipedia.org/wiki/Differentiable_manifold), smooth or [analytic](https://en.wikipedia.org/wiki/Analytic_manifold) transition maps are considered.

An even stronger restriction holds for complex manifolds: the charts are complex valued ($\phi_i\colon U_i \to \mathbb{C}^n$) and transition maps are required to be holomorphic functions.
Note that not any manifold represented using complex numbers is a complex manifold.
In particular, no manifold of odd (real) dimension can be a complex manifold.
Complex representation is a feature of [CR manifolds](https://en.wikipedia.org/wiki/CR_manifold).
Instances of [`AbstractManifold`](@ref) with complex number system `ð”½` are not required to be complex manifolds, though they are expected to be CR manifolds.

This definition of a manifold is both too restrictive and not restrictive enough.
The first aspect is manifested by, for example:
1. Manifolds with boundary which relax the definition of a chart to cases where the codomain can also be a product $\mathbb{R}^{n-1}\times[0,\infty)$.
2. Manifolds with corners which relax it even further, that is the codomain can also be a product $\mathbb{R}^{n-k}\times[0,\infty)^k$ for any $k \in [0, 1, \dots, n]$ [Joyce:2010](@cite).
3. Infinite-dimensional manifolds [KrieglMichor:1997](@cite). Though in practice we always need to select a finite-dimensional subspace to work with, the selection of this subspace can be data-driven and some consideration of the infinite case can be useful. For some examples see [SrivastavaKlassen:2016](@cite).
4. [Stratified spaces](https://ncatlab.org/nlab/show/stratified+space), which allow for example for decomposing a complicated space into manifolds, and thus dimension and charts are only considered on particular strata. There are, unfortunately, many different regularity conditions that can be imposed leading to significantly different spaces. There is some recent work on using stratified spaces for practical purposes [FeragenNue:2020](@cite), and also some mixed discrete-continuous optimization algorithms can be interpreted as exploiting stratification.

On the other hand, an atlas is insufficient for almost every algorithm that would like to exploit relationships between points.
[Topological data analysis](https://en.wikipedia.org/wiki/Topological_data_analysis) tries discovering such structure, in the form of [simplicial complexes](https://en.wikipedia.org/wiki/Simplicial_complex), directly from some available data.
JuliaManifolds focuses on the case where the structure is explicitly specified by the user through a connection.
Roughly speaking, when a manifold has additional structure attached at each point, a connection specifies how structures attached to different points are related to each other.

## Tangent space

Let's start with the most commonly encountered structure that can be attached to a point on a manifold: a tangent vector.
Let us consider an $n$-dimensional manifold $\mathcal{M}$ a point $p\in\mathcal{M}$, and a chart $\phi_i$ around $p$.
We can take any vector $v\in\mathbb{R}^n$ and define a curve $\gamma(t) = \phi_i^{-1}(\phi_i(p) + tv)$ for sufficiently small $t$.
The curve is, obviously, dependent on the selection of chart in a nonlinear way.
To deal with this problem we consider any two curves $\gamma_1, \gamma_2$ such that $\frac{d}{dt}\phi_i(\gamma_1(t))\rvert_{t=0} = \frac{d}{dt}\phi_i(\gamma_2(t))\rvert_{t=0}$ to represent the same tangent vector.
It turns out that formalizing this leads to a [tangent space](https://en.wikipedia.org/wiki/Tangent_space) that is an $n$-dimensional real vector space, and the definition in terms of $v$ provides a vector space isomorphism.

A tangent vector can be interpreted as a direction in which we may go from a point up to its first order behavior.
There is also another, equivalent [^tangent-space-equivalence] definition of a tangent vector $X$ at point $p$.
We can consider it to be the direction in which we differentiate a scalar-valued function $f\colon \mathcal{M} \to \mathbb{R}$ at $p$.

Let us consider an example: gradient descent.
We would like to optimize a function $f\colon \mathcal{M} \to \mathbb{R}$, that is find $p^{*} = \arg\min_{p \in \mathcal{M}} f(p)$.
We start at point $p_0 \in \mathcal{M}$ and through some computations determine that $X$ is the direction of steepest descent of $f$ at $p_0$.
In the typical fashion, we would like to perform a step in direction $X$.
We can follow any curve $\gamma$ that could represent $X$ for some finite time $t$.
However, this procedure can result in vastly different results depending on the choice of $\gamma$.
How do we choose which one to follow?
In some cases it doesn't matter that much and we can select whichever one can be computed the fastest.
However, often a consistent choice is required for convergence or some other desirable property of an algorithm.
A compelling solution comes in the form of an affine connection.

A curious reader may wonder why we stopped at affine functions in our definition of tangent vectors.
Surely, we could use higher-order polynomials or other families of functions to define [jets](https://ncatlab.org/nlab/show/jet+bundle) and [germs](https://ncatlab.org/nlab/show/germ), among other things [KolarSlovakMichor:1993](@cite).
We are not aware of any practical significance of such theories (apart from a few very specific examples) but who knows what the future holds.

## Connections

Broadly speaking, a connection is a structure on a fiber bundle that specifies how fibers at different points relate to each other.
In the trivial case a fiber bundle $E$ can be understood is just a product manifold $\mathcal{M} \times F$.
In general operations on a fiber bundle are expressed through a projection $\pi \colon E \to \mathcal{M}$ and local trivializations establishing the product structure on open subsets of $\mathcal{M}$.
To be more specific, each point $p\in\mathcal{M}$ has an open neighborhood $U  \subseteq \mathcal{M}$ such that $\pi^{-1}(U)$ is homeomorphic to $U \times F$, that is there is a homeomorphism $h\colon \pi^{-1}(U) \to U \times F$ such that for each $e \in E$ the projection $\pi(e)$ is equal to the first component of $h(e)$.

To give a concrete example, let's start with the tangent bundle $T\mathcal{M}$ of an $n$-dimensional manifold $\mathcal{M}$.
We can find a chart $\phi_i \colon U_i \to \mathbb{R}^n$, and thus locally identify the tangent bundle with $\mathbb{R}^n \times \mathbb{R}^n$.
The neighborhood $U_i \subseteq \mathcal{M}$ can be used to locally decompose the tangent bundle as $U_i \times \mathbb{R}^n$. [^parallelizable-manifolds]
Now we can locally write an ODE that shows us how to move a tangent vector $Y$ at $p$ to another point indicated by tangent vector $X$ at $p$:

```math
\frac{d}{dt}\begin{bmatrix}
        p_c(t)\\
        X_c(t)\\
        Y_c(t)
    \end{bmatrix} = \begin{bmatrix}
        X_c(t) \\
        -\Gamma_i(p(c), X_c(t), X_c(t)) \\
        -\Gamma_i(p(c), X_c(t), Y_c(t))
    \end{bmatrix}
```

where $p_c\colon [0, 1] \to \mathbb{R}^n$, $X_c\colon [0, 1] \to \mathbb{R}^n$, $Y_c\colon [0, 1] \to \mathbb{R}^n$ and $\Gamma_i\colon \mathbb{R}^n \times \mathbb{R}^n \times \mathbb{R}^n \to \mathbb{R}^n$ is any differentiable function.
Initial conditions for the ODE are such that $p_c(0) = \phi_i(p)$, while $X_c(0)$ and $Y_c(0)$ are coefficients of, respectively, $X$ and $Y$ in the basis of $T_p \mathcal{M}$ induced by $\phi_i$.

Solving the ODE defined in this way connects the tangent space at $p$ with the tangent space at $\phi_i^{-1}(p_c(1))$ by mapping $Y$ to the tangent vector represented by $Y_c(1)$ in the basis of $T_{\phi_i^{-1}(p_c(1))} \mathcal{M}$ induced by $\phi_i$.
The function $\Gamma_i$ defines an [affine connection](https://en.wikipedia.org/wiki/Affine_connection) for the manifold $\mathcal{M}$ [^gamma-i] in chart $i$).
The detailed investigations of differential geometry then delve into how to define affine connections in a way that makes the solution of such ODEs for different charts consistent.
When using JuliaManifolds you don't have to worry about this because we generally deal with affine connections in a consistent way but it is highly relevant when working out a new connection.
The relevant JuliaManifolds function is ``[`affine_connection`](@extref Manifolds :jl:method:`Manifolds.affine_connection-Tuple{AbstractManifold, Vararg{Any, 5}}`)``{=commonmark}

You may be curious why the same function $\Gamma_i$ appears twice in ODE defining the connection.
It is the result of one of the consistency conditions: we want the vector $X$ in which we move to be connected to its counterparts (defined by the second group of equations) in other tangent spaces.
It is, however, not strictly required for more general connections.[^other-connections]
Such connections keep the equations for $p_c$ and $X_c$ but replace the equation for $Y_c$ with something else.
In other words, the first two equations define how to move on a manifold, while the third one defines how to connect fibers we cross when we move.

Note that, as a result of independence from selection of the chart, one usually selects a chart in which solving the affine connection ODE is the easiest.
In some special cases (like spheres) there even exist closed-form solutions.
To support such efficient computation, one can directly use the functions [`exp`](@ref), [`log`](@ref) and [`parallel_transport_direction`](@ref).

While the conditions on the form in which fibers may be connected appear quite restrictive, in practice they turn out to still be very general.
We thus need some additional guidelines to select a connection for our manifold.
There are multiple available options.
The following list discusses the most prominent ones.

1. When the manifold is specified through an [embedding](https://en.wikipedia.org/wiki/Embedding), [pushforward](https://en.wikipedia.org/wiki/Pushforward_(differential)) or [quotient](https://en.wikipedia.org/wiki/Quotient_space_(topology)) based on a space with known geometry, we can use it to define a connection.
2. Sometimes we have additional structure, for example Riemannian, Finsler or Lie (discussed in following sections) which imposes heavy restrictions.
3. If we want to make a physical model, our constraints are dictated by physical principles and measurements. Note that the language used in this tutorial is very popular in modern physics.

Fitting the application is, however, always the primary criterion.
JuliaManifolds prioritizes support for things that actually are practically relevant so starting from what's already available is a good approach.

## Between Riemann and Finsler

In this section we focus on manifolds and their tangent bundles.
There are two popular ways in which we can specify their structure in a much less flexible way than general connections: Finsler and Riemann.[^finsler-riemann-chern]
In return we get more structure to work with, and can thus generically express more algorithms.

The initial premise can be expressed by the desire to measure distance along a path $\gamma \colon [a, b] \to \mathbb{M}$ using the formula
```math
I(\gamma) = \int_a^b F(\gamma(t), \dot{\gamma}(t)) dt
```
where $F \colon T\mathcal{M} \to [0, \infty)$ is a certain scalar function on tangent bundle called Finsler metric.[BaoChernShen:2000](@cite)
It has the following properties:

* $F$ is smooth on $TM \ \{0\}$.
* For all $p\in \mathcal{M}$, $X \in T_p \mathcal{M}$ and $\lambda \geq 0$ the metric is homogeneous: $F(p, \lambda X) = \lambda F(p, X)$.
* Strong convexity: at each $p\in \mathcal{M}$ the Hessian of $X \mapsto \frac{1}{2}F^2(p, X)$ is positive definite.[^no-strong-convexity]. This Hessian $g(p)$ is called the fundamental tensor.
For each point $p$ the function $X \mapsto F(p, X)$ is a Minkowski norm on $T_p\mathcal{M}$, that is
* $F(p, X) > 0$ for all $X \neq 0$,
* $F(p, X_1 + X_2) \leq F(p, X_1) + F(p, X_2)$,
* $g(X_1, X_2) \leq F(p, X_1)F(p, X_2)$.[^fundamental-inequality]
The Finsler metric can be calculated using [`norm`](@ref).

Despite a very generic description, Finsler manifolds provide a rich structure.
We can measure distances between points as $d(p, q) = \inf_{\gamma} L(\gamma)$, where the infimum is taken across all curves such that $\gamma(0) = p$ and $\gamma(1) = q$.
It is handled by the [`distance`](@ref) function.
There is also a unique connection, called Chern connection, that arises from $F$.
It is a generalization of the famous [Levi-Civita connection](https://en.wikipedia.org/wiki/Levi-Civita_connection) for Riemannian manifolds.
It is, however, much more technical to work with than the Riemannian case [BaoChernShen:2000](@cite).

Many possible restrictions have been considered, for example:

* Reversibility (or, equivalently, absolute homogeneity), that is $F(p, \lambda X) = \lvert \lambda \rvert F(p, X)$ for all $\lambda \in \mathbb{R}$.
* Riemannian manifolds restrict the metric function $F$ to a quadratic forms in $X$ at each $p$. Such forms give rise to an inner product on each tangent space, see [`inner`](@ref).

JuliaManifolds was designed based on Riemannian manifolds because they are much more simple to work with and more common in applications.
However, many parts can still be generalized to Finsler manifolds, pseudo-Riemannian manifolds or even pseudo-Finsler manifolds.

## Lie groups




## Fibers with more structure



[^chart-number-system]: Sometimes other number systems are considered for the codomain of charts, most notably complex numbers. This discussion is restricted to the real case because it's general enough for practical purposes. Complex atlases can be represented as real atlases with real and imaginary parts separated. Quaternionic manifolds are most easily expressed though fiber bundles. [Other generalizations](https://math.stackexchange.com/a/581087) often lead to spaces that are no longer manifolds.

[^tangent-space-equivalence]: These definitions are equivalent for finite-dimensional manifolds but not for all infinite-dimensional ones. You can see [kinematic tangent space](https://ncatlab.org/nlab/show/kinematic+tangent+space) for more details.

[^parallelizable-manifolds]: Manifolds whose tangent bundle is trivial (and thus we can select $U_i=\mathcal{M}$) are called [parallelizable](https://en.wikipedia.org/wiki/Parallelizable_manifold).

[^gamma-i]: In the specific case of a metric connection it is called a [Christoffel symbol](https://en.wikipedia.org/wiki/Christoffel_symbols).

[^other-connections]: See for example [Ehresmann connection](https://en.wikipedia.org/wiki/Ehresmann_connection) and its different variants.

[^finsler-riemann-chern]: Historically Finsler manifolds are very close to what Riemann actually studied, and what is now known as Riemannian manifolds has a quadratic restriction that was added later. See [Chern:1996](@cite) for more details.

[^no-strong-convexity]: This requirement can be slightly relaxed to nondegeneracy and many properties still hold [JavaloyesSoares:2015](@cite).

[^fundamental-inequality]: This condition can be expressed in many equivalent forms. The one written here is not the most simple one but possibly the easiest to interpret, since it looks similar to the [Cauchy-Schwarz inequality](https://en.wikipedia.org/wiki/Cauchy%E2%80%93Schwarz_inequality). 
