[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
DocumenterCodeBlocks = "b6400b83-267f-4b55-9fd8-bffc853bdfd8"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"
DocumenterLandingPage = "1c52b33b-3e2f-4e99-b3b5-a6ad63f0d6d2"
ManifoldsBase = "3362f125-f0bb-47a3-aa74-596ffd7ef2fb"

[compat]
Documenter = "1"
DocumenterCitations = "1.2"
DocumenterCodeBlocks = "1.5.0"
DocumenterInterLinks = "1.1"
DocumenterLandingPage = "0.2.0"
ManifoldsBase = "1,2"

[sources]
ManifoldsBase = { path = ".." }
